package com.uiautomation.enums;

public enum ConfigProperties {
    URL,
    BROWSER,
    OVERRIDEREPORTS,
    PASSEDTESTSCREENSHOTS,
    FAILEDTESTSCREENSHOTS,
    SKIPPEDTESTSSCREENSHOTS,
    RETRYFAILEDTESTS

}
